version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=auth
    ports:
      - "5001:5000"
    networks:
      - petstore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 5
      timeout: 5s

  products:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=products
    ports:
      - "5002:5000"
    networks:
      - petstore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      retries: 5
      timeout: 5s

  cart:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=cart
    ports:
      - "5005:5000"
    networks:
      - petstore_network

  orders:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=orders
    ports:
      - "5006:5000"
    networks:
      - petstore_network


  categories:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=categories
    ports:
      - "5003:5000"
    networks:
      - petstore_network

  pets:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=pets
    ports:
      - "5007:5000"
    networks:
      - petstore_network

  search:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=search
    ports:
      - "5004:5000"
    networks:
      - petstore_network

  reviews:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    environment:
      - SERVICE_NAME=reviews
    ports:
      - "5008:5000"
    networks:
      - petstore_network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVICE_NAME=api-gateway
    ports:
      - "5000:5000"
    networks:
      - petstore_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
 
    networks:
      - petstore_network

networks:
  petstore_network:
    driver: bridge
