openapi: 3.0.0
info:
  title: Reviews API
  description: API for managing product reviews
  version: 1.0.0

paths:
  /api/reviews:
    get:
      summary: Retrieve all reviews
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
        - name: sort_by
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
        - name: order
          in: query
          description: Sorting order (asc or desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
      responses:
        "200":
          description: Successful response
    post:
      summary: Submit a product review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                product_id:
                  type: string
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                comment:
                  type: string
              required:
                - user_id
                - product_id
                - rating
      responses:
        "201":
          description: Review submitted successfully

  /api/reviews/{review_id}:
    get:
      summary: Retrieve a review by ID
      parameters:
        - name: review_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Review found
        "404":
          description: Review not found

  /api/reviews/product/{product_id}:
    get:
      summary: Retrieve all reviews for a product
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Product not found
