openapi: 3.0.0
info:
  title: Search API
  description: API for searching products across categories
  version: 1.0.0
paths:
  /api/search:
    get:
      summary: Search for products
      parameters:
        - name: q
          in: query
          description: Keyword for searching product names and categories
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
        - name: sort_by
          in: query
          description: Field to sort by
          required: false
          schema:
            type: string
        - name: order
          in: query
          description: Sorting order (asc or desc)
          required: false
          schema:
            type: string
            enum: [asc, desc]
      responses:
        "200":
          description: Successful response
        "400":
          description: Invalid request
